spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/news
    username: postgres
    password: root
  jpa:
    show-sql: true
  liquibase:
    enabled: true
    drop-first: true
    clear-checksums: true
server:
    port: 8082