spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: news-data-service
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  data:
    web:
      pageable:
        default-page-size: 5
        max-page-size: 30
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8079/eureka/
