spring:
  cache:
    redis:
      time-to-live: 3600
app:
  cache:
    enable: true
    type: LFU
    size: 1000
    time-to-live: 3600
  jwt:
    access:
      secret:
      expiration:
    refresh:
      secret:
      expiration: