spring:
  cloud:
    openfeign:
      client:
        config:
          user-data-service:
            url: http://localhost:8081
  application:
    name: user-service
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cache:
    type: NONE

